### ISSUE TITLE
mod folder don't appear in MainWindow if DarkSouls.exe is not auto-detected

### ISSUE THREAD

**Issue by aikoncwd** [Wulf2k/DS-ModMan#1]
My Steam is installed on a custom path `D:\Games\Steam`.

**Issue**
The function `ScanForDarkSoulsDataDir()` can't locate my ExeFile and the variable `dataPath` is not set. Then the function `LoadMods()` fails because `dataPath` have a wrong value  

I don't have vb.net installed on my computer, so I can't send a Pull Request, but I think you can identify easy. Line 210 from file `Form1.vb`. Maybe you can add some code to set the value of `dataPath` after calling the function `btnBrowse_Click()`

**Comment by Wulf2k** [comment]
datapath is now assigned on a successful CheckEXE instead of in the autoscan.
